require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Exclude  

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - 'Rakefile'
    - 'lib/**/*'
    - 'bin/**/*'
  Exclude:
    - 'bin/setup'
    - 'Gemfile.lock'
    - 'Gemfile'
    - 'gemfiles/**/*'
    - '**/*.json'
    - '**/*.yml'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false 
  Max: 12

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false

Layout/LineLength:
  Enabled: true
  Max: 125
