require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Exclude  
    - Include  

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "Rakefile"
    - "Gemfile"
    - "*.gemspec"
    - 'Rakefile'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**/*.rb'
    - '.simplecov'
  Exclude:
    - 'bin/setup'
    - 'Gemfile.lock'
    - 'gemfiles/**/*'
    - '**/*.json'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Enabled: true
  Max: 125

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false 
  Max: 12

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

Style/HashEachMethods:
  Enabled: true
  
Style/HashTransformKeys:
  Enabled: true
  
Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true